# Generated by Django 4.0.6 on 2022-07-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
