# Generated by Django 4.0.6 on 2022-07-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_example_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='image_second',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
